openapi: "3.0.3"

info:
  title: "CityXR Server API"
  version: "1.0.0"

servers:
  - url: /v1
    description: Version 1 of the api.

paths:
  /data/{datasource_id}/latest:
    get:
      operationId: app.views.get_latest_data_for_source
      summary: Gets the latest data points from the source.
      parameters:
        - name: datasource_id
          in: path
          description: UUID of the datasource.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: |-
            Data object with the latest values from the source.
          content:
            application/json:
              schema:
                type: object
        "404":
          description: |-
            Error if the given data source doesn't exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Message about missing data source."

  /datasources:
    get:
      operationId: app.views.get_available_data_sources
      summary: Gets the available datasources.
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    createdAt:
                      type: string
                      description: |-
                        RFC3339 timestamp of when the datasource was booted.
                    isDisabled:
                      type: boolean
                      description: |-
                        Whether or not the datasource is currently running.
                    config:
                      type: object
                      additionalProperties:
                        type: string
                        description: |-
                          Datatype of the column of the datasource.

  /heartbeat:
    get:
      operationId: app.views.heartbeat
      summary: Gets heartbeat information, server uptime, etc.
      responses:
        "200":
          description: |-
            Uptime and boot time about the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  bootTime:
                    type: string
                    description: "RFC3339 time server was started."
                  uptime:
                    type: number
                    description: "Uptime in seconds of server."
