openapi: "3.0.3"

info:
  title: "CityXR Server API"
  version: "1.0.0"

servers:
  - url: /v1
    description: Version 1 of the api.

paths:
  /datasources:
    get:
      operationId: app.views.get_available_data_sources
      summary: Gets the available datasources
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object

  /heartbeat:
    get:
      operationId: app.views.heartbeat
      summary: Gets heartbeat information, server uptime, etc.
      responses:
        "200":
          description: |-
            Uptime and boot time about the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  bootTime:
                    type: string
                    description: "RFC3339 time server was started."
                  uptime:
                    type: number
                    description: "Uptime in seconds of server."
