# VERSION 1.0 (apache-superset)
# AUTHOR: Abhishek Sharma<abhioncbr@yahoo.com>
# DESCRIPTION: apache superset docker-compose.yml
# Modified/revamped version of the https://github.com/apache/incubator-superset/blob/master/contrib/docker/docker-compose.yml

version: "3"
services:
  superset:
    image: abhioncbr/docker-superset:${SUPERSET_VERSION}
    restart: always
    environment:
      SUPERSET_ENV: ${SUPERSET_ENV}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8088:8088
      - 5555:5555
    volumes:
      - ../config/:/home/superset/config/
